# Generated by Django 4.2.27 on 2025-12-17 23:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of week for recurring availability",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Start time of availability window"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="End time of availability window"),
                ),
                (
                    "effective_from",
                    models.DateField(
                        blank=True,
                        help_text="Start date (optional, for temporary changes)",
                        null=True,
                    ),
                ),
                (
                    "effective_until",
                    models.DateField(
                        blank=True,
                        help_text="End date (optional, for temporary changes)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this availability is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability",
                "verbose_name_plural": "Availabilities",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="BlockedTime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_datetime",
                    models.DateTimeField(help_text="Start of blocked period"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(help_text="End of blocked period"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation/Leave"),
                            ("busy", "Busy"),
                            ("personal", "Personal"),
                            ("holiday", "Public Holiday"),
                            ("other", "Other"),
                        ],
                        default="busy",
                        help_text="Reason for blocking time",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Optional description", max_length=255
                    ),
                ),
                (
                    "is_all_day",
                    models.BooleanField(default=False, help_text="Block entire day(s)"),
                ),
            ],
            options={
                "verbose_name": "Blocked Time",
                "verbose_name_plural": "Blocked Times",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(help_text="Meeting title", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Meeting description or agenda"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Meeting start time (timezone-aware)"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(help_text="Meeting end time (timezone-aware)"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Meeting duration in minutes (5-480)",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(480),
                        ],
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Location"),
                            ("virtual", "Virtual Meeting"),
                            ("hybrid", "Hybrid (Physical + Virtual)"),
                        ],
                        default="virtual",
                        help_text="Type of meeting location",
                        max_length=20,
                    ),
                ),
                (
                    "physical_address",
                    models.CharField(
                        blank=True,
                        help_text="Physical address (e.g., Westlands, Nairobi)",
                        max_length=500,
                    ),
                ),
                (
                    "physical_landmark",
                    models.CharField(
                        blank=True,
                        help_text="Nearby landmark for directions",
                        max_length=255,
                    ),
                ),
                (
                    "virtual_platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("zoom", "Zoom"),
                            ("google_meet", "Google Meet"),
                            ("ms_teams", "Microsoft Teams"),
                            ("other", "Other"),
                        ],
                        help_text="Virtual meeting platform",
                        max_length=20,
                    ),
                ),
                (
                    "virtual_link",
                    models.URLField(blank=True, help_text="Virtual meeting link"),
                ),
                (
                    "virtual_meeting_id",
                    models.CharField(
                        blank=True,
                        help_text="Meeting ID (for Zoom, Teams, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "virtual_passcode",
                    models.CharField(
                        blank=True,
                        help_text="Meeting passcode if required",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        help_text="Current meeting status",
                        max_length=20,
                    ),
                ),
                (
                    "recurrence_pattern",
                    models.CharField(
                        choices=[
                            ("none", "No Recurrence"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Every Two Weeks"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        default="none",
                        help_text="Recurrence pattern",
                        max_length=20,
                    ),
                ),
                (
                    "recurrence_end_date",
                    models.DateField(
                        blank=True,
                        help_text="End date for recurring meetings",
                        null=True,
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False, help_text="Private meeting (hidden from search)"
                    ),
                ),
                (
                    "allow_guest_participants",
                    models.BooleanField(
                        default=False, help_text="Allow non-registered users to join"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Meeting notes or minutes"),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, help_text="Whether reminder has been sent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("tentative", "Tentative"),
                        ],
                        default="pending",
                        help_text="Participant response status",
                        max_length=20,
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, help_text="Optional message with response"
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, help_text="When participant responded", null=True
                    ),
                ),
                (
                    "attended",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether participant attended the meeting",
                        null=True,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_responses",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Participant",
                "verbose_name_plural": "Meeting Participants",
                "ordering": ["created_at"],
            },
        ),
    ]
