# Generated by Django 4.2.27 on 2025-12-17 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="organizer",
            field=models.ForeignKey(
                help_text="Meeting organizer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_meetings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="parent_meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent meeting for recurring instances",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_instances",
                to="meetings.meeting",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="participants",
            field=models.ManyToManyField(
                help_text="Meeting participants",
                related_name="meetings",
                through="meetings.MeetingParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blockedtime",
            name="user",
            field=models.ForeignKey(
                help_text="User this blocked time belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_times",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="user",
            field=models.ForeignKey(
                help_text="User this availability belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingparticipant",
            unique_together={("meeting", "user")},
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["start_time"], name="meetings_me_start_t_7a37c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["organizer", "start_time"],
                name="meetings_me_organiz_dadae7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["status"], name="meetings_me_status_14fbb6_idx"),
        ),
        migrations.AddIndex(
            model_name="availability",
            index=models.Index(
                fields=["user", "day_of_week"], name="meetings_av_user_id_e908d5_idx"
            ),
        ),
    ]
