# Generated by Django 4.2.27 on 2025-12-17 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("invitation", "Meeting Invitation"),
                            ("update", "Meeting Update"),
                            ("cancellation", "Meeting Cancellation"),
                            ("reminder", "Meeting Reminder"),
                            ("response", "Participant Response"),
                        ],
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        help_text="Delivery channel",
                        max_length=10,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Notification subject", max_length=255),
                ),
                ("message", models.TextField(help_text="Notification message body")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was sent", null=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When notification was delivered",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if delivery failed"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of delivery attempts"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External service ID (e.g., Africa's Talking message ID)",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_invitations", models.BooleanField(default=True)),
                ("email_updates", models.BooleanField(default=True)),
                ("email_cancellations", models.BooleanField(default=True)),
                ("email_reminders", models.BooleanField(default=True)),
                ("sms_invitations", models.BooleanField(default=False)),
                ("sms_updates", models.BooleanField(default=False)),
                ("sms_cancellations", models.BooleanField(default=True)),
                ("sms_reminders", models.BooleanField(default=True)),
                (
                    "reminder_time_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Minutes before meeting to send reminder"
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True, help_text="Start of quiet hours", null=True
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, help_text="End of quiet hours", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
    ]
