# Generated by Django 4.2.27 on 2025-12-17 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                help_text="User these preferences belong to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="Related meeting",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="meetings.meeting",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                help_text="Notification recipient",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "status"], name="notificatio_user_id_7088ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["meeting", "notification_type"],
                name="notificatio_meeting_de02c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "created_at"], name="notificatio_status_9a4505_idx"
            ),
        ),
    ]
